package com.tradingplatform.app.ui.screens.setup

import android.content.Intent
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.tradingplatform.app.domain.usecase.pairing.ParseSetupQrUseCase
import com.tradingplatform.app.domain.usecase.pairing.ProvisionMobileVpnUseCase
import com.tradingplatform.app.domain.usecase.setup.MarkSetupCompletedUseCase
import com.tradingplatform.app.vpn.VpnState
import com.tradingplatform.app.vpn.WireGuardManager
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import timber.log.Timber
import javax.inject.Inject

/**
 * UiState for [SetupScreen].
 *
 * Lifecycle:
 * - [Scanning]   — waiting for the user to scan the onboarding QR code
 * - [Connecting] — QR parsed, WireGuard tunnel being established
 * - [Connected]  — tunnel up, navigating to Login
 * - [Error]      — QR parse failure or VPN error, retryable via [SetupViewModel.retry]
 * - [VpnConsentRequired] — Android must authorise the app to create a VPN: the screen launches
 *   the system dialog once (`launched == false`), then reports via [SetupViewModel.onVpnConsentResult]
 * - [VpnConsentDenied]   — the user refused the dialog; [SetupViewModel.retryVpnConsent] re-asks
 *   (provisioning is already done — rescanning the QR is not needed)
 */
sealed interface SetupUiState {
    data object Scanning : SetupUiState
    data object Connecting : SetupUiState
    data object Connected : SetupUiState
    data class Error(val message: String) : SetupUiState
    data class VpnConsentRequired(val launched: Boolean = false) : SetupUiState
    data class VpnConsentDenied(val message: String = VPN_CONSENT_DENIED_MESSAGE) : SetupUiState
}

/** Shown by SetupScreen and VpnSettingsScreen when the user refuses the VPN consent dialog. */
const val VPN_CONSENT_DENIED_MESSAGE =
    "Autorisation VPN refusée — le tunnel est requis pour utiliser l'application"

/**
 * ViewModel for the initial onboarding setup screen.
 *
 * Mobile-provisioning flow:
 *   1. user scans the QR served on /download (no private material in it)
 *   2. [ParseSetupQrUseCase] validates structure + expiry
 *   3. [ProvisionMobileVpnUseCase] generates the WG keypair on-device, computes
 *      the HMAC pin_proof, calls /v1/me/mobile-provisioning/{id}/register over
 *      public 8443, persists the result, and asks [WireGuardManager] to bring
 *      the tunnel up
 *   4. once [VpnState.Connected] is observed, persists the completion flag via
 *      [MarkSetupCompletedUseCase] and transitions to [SetupUiState.Connected]
 *
 * Security invariants:
 * - The WireGuard private key is generated by the phone, never reaches the
 *   server, never appears in any log line — [REDACTED] applies even in debug.
 * - [ProvisionMobileVpnUseCase] is the only place that touches the private key
 *   in memory; `EncryptedDataStore` is its persistent home.
 *
 * This ViewModel never touches `EncryptedDataStore` directly (CLAUDE.md §2) — completion is
 * persisted via [MarkSetupCompletedUseCase], which goes through [SetupRepository][com.tradingplatform.app.domain.repository.SetupRepository].
 */
@HiltViewModel
class SetupViewModel @Inject constructor(
    private val parseSetupQrUseCase: ParseSetupQrUseCase,
    private val provisionMobileVpnUseCase: ProvisionMobileVpnUseCase,
    private val wireGuardManager: WireGuardManager,
    private val markSetupCompletedUseCase: MarkSetupCompletedUseCase,
) : ViewModel() {

    private val _uiState = MutableStateFlow<SetupUiState>(SetupUiState.Scanning)
    val uiState: StateFlow<SetupUiState> = _uiState.asStateFlow()

    /** Tracks the in-flight QR/VPN coroutine so [cancelConnecting] can abort it. */
    private var setupJob: Job? = null

    /**
     * Called by the [QrScannerView] callback when a QR code has been detected.
     *
     * Idempotent — if already past [SetupUiState.Scanning], the call is ignored
     * (QrScannerView fires the callback only once per scan, but guard here as well).
     */
    fun onQrScanned(raw: String) {
        if (_uiState.value !is SetupUiState.Scanning) return

        setupJob = viewModelScope.launch {
            val parseResult = parseSetupQrUseCase(raw)
            val setupData = parseResult.getOrElse { error ->
                Timber.w("SetupViewModel: QR parse failed — ${error.message}")
                _uiState.value = SetupUiState.Error(
                    error.localizedMessage ?: "QR code non reconnu"
                )
                return@launch
            }

            _uiState.value = SetupUiState.Connecting

            // ProvisionMobileVpnUseCase: keypair-on-device + HMAC + /register +
            // persist + connect. Private key never leaves the use case.
            val provisionResult = provisionMobileVpnUseCase(setupData)
            provisionResult.onFailure { error ->
                Timber.w("SetupViewModel: provisioning failed — ${error.message}")
                _uiState.value = SetupUiState.Error(
                    error.localizedMessage ?: "Échec du provisioning"
                )
                return@launch
            }

            awaitTunnel()
        }
    }

    /**
     * Observes the VPN state until it reaches a terminal state.
     * first { } suspends until the predicate is true, then returns —
     * avoids an infinite collect loop that return@collect cannot break.
     */
    private suspend fun awaitTunnel() {
        val terminalState = wireGuardManager.state.first { vpnState ->
            vpnState is VpnState.Connected ||
                vpnState is VpnState.Error ||
                vpnState is VpnState.ConsentRequired
        }
        when (terminalState) {
            is VpnState.Connected -> {
                markSetupCompletedUseCase()
                _uiState.value = SetupUiState.Connected
                Timber.i("SetupViewModel: WireGuard connected, setup_completed=true")
            }
            is VpnState.Error -> {
                _uiState.value = SetupUiState.Error(
                    terminalState.message.ifBlank { "Erreur de connexion VPN" }
                )
            }
            is VpnState.ConsentRequired -> {
                // Fresh device (or another VPN app took over): Android's consent dialog is
                // needed before GoBackend may bring the tunnel UP. The config is kept by
                // WireGuardManager — no need to re-provision.
                Timber.i("SetupViewModel: VPN consent required")
                _uiState.value = SetupUiState.VpnConsentRequired()
            }
            else -> Unit // Cannot happen — first { } only returns the states above
        }
    }

    /** Intent of the system VPN consent dialog, or null when consent is already granted. */
    fun vpnConsentIntent(): Intent? = wireGuardManager.prepareIntent()

    /** The screen launched the consent dialog — prevents a second launch on recomposition. */
    fun onVpnConsentLaunched() {
        if (_uiState.value is SetupUiState.VpnConsentRequired) {
            _uiState.value = SetupUiState.VpnConsentRequired(launched = true)
        }
    }

    /**
     * Result of the system VPN consent dialog (RESULT_OK → [granted]).
     * Granted → back to [SetupUiState.Connecting] and the pending connect is replayed.
     * Denied → [SetupUiState.VpnConsentDenied] with an explicit message and a retry button.
     */
    fun onVpnConsentResult(granted: Boolean) {
        if (_uiState.value !is SetupUiState.VpnConsentRequired) return
        if (!granted) {
            Timber.w("SetupViewModel: VPN consent denied by the user")
            _uiState.value = SetupUiState.VpnConsentDenied()
            return
        }
        _uiState.value = SetupUiState.Connecting
        // retryAfterConsent() publishes Connecting synchronously: awaitTunnel() cannot read the
        // stale ConsentRequired and loop.
        wireGuardManager.retryAfterConsent()
        setupJob = viewModelScope.launch { awaitTunnel() }
    }

    /** "Réessayer" after a denial: asks the screen to launch the consent dialog again. */
    fun retryVpnConsent() {
        if (_uiState.value !is SetupUiState.VpnConsentDenied) return
        _uiState.value = SetupUiState.VpnConsentRequired()
    }

    /**
     * Resets the state back to [SetupUiState.Scanning] after an error.
     * The QrScannerView will re-arm its scan on the next recomposition.
     */
    fun retry() {
        _uiState.value = SetupUiState.Scanning
    }

    /**
     * Cancels an in-flight VPN connection attempt and returns to [SetupUiState.Scanning].
     * Called when the user presses "Annuler" or system back during [SetupUiState.Connecting].
     *
     * No-op if called outside Connecting state (e.g. from Scanning, where system back
     * should fall through to exit the app as the normal root-screen behavior).
     */
    fun cancelConnecting() {
        if (_uiState.value !is SetupUiState.Connecting) return
        setupJob?.cancel()
        setupJob = null
        wireGuardManager.disconnect()
        _uiState.value = SetupUiState.Scanning
        Timber.i("SetupViewModel: connection cancelled by user")
    }
}
